name: 'Check for PR labels that block merging'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
  merge_group:

jobs:
  ensure-blocking-pr-labels-absent:
    if: ${{ github.event_name != 'merge_group' }} # Skip this step for merge_group events
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@0543b5929698c71e3ccc6ed24eac87825669b5de # v3.5.0
        with:
          is-high-risk-environment: false
          persist-credentials: false
      - name: Run command
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            if (context.payload.pull_request.labels.some((label) => label.name === 'DO-NOT-MERGE')) {
              core.setFailed(
                "PR cannot be merged because it contains the label 'DO-NOT-MERGE'."
              );
            }
