name: Main

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/heads/main') }}

jobs:
  analyse-code:
    name: Code scanner
    uses: ./.github/workflows/security-code-scanner.yml
    permissions:
      actions: read
      contents: read
      security-events: write
    secrets:
      SECURITY_SCAN_METRICS_TOKEN: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
      APPSEC_BOT_SLACK_WEBHOOK: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}

  build-lint-test:
    if: "github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'labeled' && github.event.action != 'unlabeled')"
    name: Build, lint, and test
    uses: ./.github/workflows/build-lint-test.yml

  require-changelog-updates-for-pull-requests:
    name: Require changelog updates for pull requests
    uses: ./.github/workflows/require-changelog-updates-in-prs.yml

  all-jobs-complete:
    name: All jobs complete
    runs-on: ubuntu-latest
    needs:
      - analyse-code
      - build-lint-test
      - require-changelog-updates-for-pull-requests
    outputs:
      passed: ${{ steps.set-output.outputs.passed }}
    steps:
      - name: Set passed output
        id: set-output
        run: echo "passed=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-complete
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-complete.outputs.passed }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi

  is-release:
    name: Determine whether this is a release merge commit
    needs: build-lint-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    steps:
      - id: is-release
        uses: MetaMask/action-is-release@dc4672b05e3b1d464cdaf783579b04a4e43f8b02
        with:
          commit-starts-with: 'Release [version],Release v[version],Release/[version],Release/v[version],Release `[version]`'

  publish-release:
    name: Publish release
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
