name: Require changelog updates for pull requests

on:
  workflow_call:

jobs:
  require-changelog-updates-for-pull-requests:
    if: github.event_name == 'pull_request'
    uses: MetaMask/github-tools/.github/workflows/changelog-check.yml@91e349d177db2c569e03c7aa69d2acb404b62f75
    with:
      base-branch: ${{ github.event.pull_request.base.ref }}
      head-ref: ${{ github.head_ref }}
      labels: ${{ toJSON(github.event.pull_request.labels) }}
      pr-number: ${{ github.event.pull_request.number }}
      repo: ${{ github.repository }}
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}

  dont-require-changelog-updates-for-pushes:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - run: |
          echo "Skipping changelog check"
